spring:
  application:
    name: msvc-filestorage
  config:
    import: configserver:http://localhost:8888/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8001

